### ISSUE TITLE
chembl.zip missing?

### ISSUE THREAD

**Issue by lenselinkbart** [Dierme/latent-gan#4]
Hello, 

I was trying to run the model on my own smiles file, this doesn't seem to work.
Where can I retrieve the chembl.zip file?;
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from encode import encode
  File "/data/Projects/de-novo/latent-gan/encode.py", line 4, in <module>
    from autoencoder import autoencoder
  File "/data/Projects/de-novo/latent-gan/autoencoder/autoencoder.py", line 22, in <module>
    model = load_model()
  File "/data/Projects/de-novo/latent-gan/autoencoder/autoencoder.py", line 18, in load_model
    model = ddc.DDC(model_name=path)
  File "/data/software/conda/envs/latent-gan/lib/python3.6/site-packages/ddc_pub-0.3-py3.6.egg/ddc_pub/ddc_v3.py", line 238, in __init__
    self.__load(self.model_name)
  File "/data/software/conda/envs/latent-gan/lib/python3.6/site-packages/ddc_pub-0.3-py3.6.egg/ddc_pub/ddc_v3.py", line 820, in __load
    with zipfile.ZipFile(model_name + ".zip", "r") as zip_ref:
  File "/data/software/conda/envs/latent-gan/lib/python3.6/zipfile.py", line 1113, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/data/Projects/de-novo/latent-gan/autoencoder/chembl.zip'

**Comment by SeemonJ** [comment]
Hi,

There is a bug on the code if no model has been entered, as the new default name of the pretrained chembl model should be chembl_pretrained.zip. The default model version if no model has been assigned refers to an old name of the pretrained chembl model.

This was missed when I renamed the pretrained model files for a nicer structure, I will put the correct chembl model as the default. Thanks for raising this issue.

**Comment by Dierme** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test](https://trello.com/c/Sw2aAnhw/20-test)
